Study/ShenQi/Controllers/WabaoController.cs
using Chloe;
using Chloe.SQLite;
using Framework.Common.Extension;
using Highsoft.Web.Mvc.Charts;
using ShenQi.Models;
using SqlliteAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShenQi.Controllers
{
    public class WabaoController : Controller
    {
        // GET: Wabao
        public ActionResult DataSearch(string enddate)
        {
            string shortdate = DateTime.Now.ToString("yyyy-MM-dd");
            if (!enddate.IsNull())
            {
                shortdate = enddate;
            }
         
            DateTime dt = Convert.ToDateTime(shortdate).AddDays(-2);
            DateTime dt2 = Convert.ToDateTime(shortdate).AddDays(+1);
            SQLiteContext dbcontext = new SQLiteContext(new SQLiteConnectionFactory("Data Source=" + System.AppDomain.CurrentDomain.BaseDirectory + "\\Chloe.db;Version=3;Pooling=True;Max Pool Size=100;"));
            IQuery<WowPower_RD> qd = dbcontext.Query<WowPower_RD>();
            List<WowPower_RD> xddlst = qd.Where(x => x.modify > dt && x.modify < dt2).ToList();
            List<WowPower_RD> now = xddlst.Where(x => x.shortdate == shortdate).ToList();
            List<WowPower_RD> yes = xddlst.Where(x => x.shortdate == Convert.ToDateTime(shortdate).AddDays(-1).ToString("yyyy-MM-dd")).ToList();
            List<WowPower_RD> last = xddlst.Where(x => x.shortdate == Convert.ToDateTime(shortdate).AddDays(-2).ToString("yyyy-MM-dd")).ToList();
            List<WabaoVM> vmlst = new List<WabaoVM>();
            foreach (var item in now)
            {
                var iy = yes.Where(x => x.gamename == item.gamename).ToList();
                var il = last.Where(x => x.gamename == item.gamename).ToList();
                double total_now = item.deposit * item.hotscore;
                double total_yes = iy.Count > 0 ? iy.FirstOrDefault().deposit * iy.FirstOrDefault().hotscore : 0;
                double total_last = il.Count > 0 ? il.FirstOrDefault().deposit * il.FirstOrDefault().hotscore : 0;
                double hotscore_yes = iy.Count > 0 ? iy.FirstOrDefault().hotscore : 0;

                vmlst.Add(new WabaoVM()
                {
                    gamename = item.gamename,
                    clicks = item.clicks,
                    deposit = item.deposit,
                    hotscore_now = item.hotscore,
                    hotscore_yes = iy.FirstOrDefault().hotscore,
                    reward = item.reward,
                    wyday = item.reward/item.clicks/item.deposit *10000,
                    total_now = total_now,
                    zje_now = total_now - total_yes,
                    zje_yes = total_yes - total_last

                });
            
            }
            ViewBag.zje_yes_total = vmlst.Sum(x => x.zje_yes);
            ViewBag.zje_now_total = vmlst.Sum(x => x.zje_now);
            ViewBag.now_total = vmlst.Sum(x => x.total_now);
            ViewBag.vmlst = vmlst;
            ViewBag.Date = shortdate;
            return View();
        }

        public ActionResult Pivot()
        {

            DateTime dt = DateTime.Now.AddDays(-11); ;
            string shortdate = DateTime.Now.ToString("yyyy-MM-dd");
            SQLiteContext dbcontext = new SQLiteContext(new SQLiteConnectionFactory("Data Source=" + System.AppDomain.CurrentDomain.BaseDirectory + "\\Chloe.db;Version=3;Pooling=True;Max Pool Size=100;"));
            IQuery<WowPower_RD> qd = dbcontext.Query<WowPower_RD>();
            List<WowPower_RD> xddlst = qd.Where(x=>x.modify>dt).ToList();
           
            var t = from p in xddlst.AsEnumerable() group p by p.shortdate into g select new { g.Key, total = g.Sum(p => p.deposit * p.hotscore) };
            var t2 = t.ToList();
            List<string> xlst = new List<string>();
            List<LineSeriesData> lst = new List<LineSeriesData>();
            for (int i = 1; i < t2.Count; i++)
            {
                xlst.Add(t2[i].Key);
                lst.Add(new LineSeriesData()
                {
                    Y=(t2[i].total - t2[i-1].total)/100000000
                });
            }
            
         
            ViewData["x"] = xlst;
            ViewData["y"] = lst;
            return View();
        }
    }
}

Study/ShenQi/Controllers/XwowmallController.cs
using Chloe;
using Chloe.Entity;
using Chloe.SQLite;
using Framework.MongoDB;
using Newtonsoft.Json;
using ShenQi.Excel;
using ShenQi.Models;
using SqlliteAccess;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ShenQi.Controllers
{
   
    public class XwowmallController : Controller
    {
        #region 报表分析
        // GET: Xwowmall
        public ActionResult Pivot()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetPivottable()
        {
            string shortdate = DateTime.Now.ToString("yyyy-MM-dd");
            SQLiteContext dbcontext = new SQLiteContext(new SQLiteConnectionFactory("Data Source=" + System.AppDomain.CurrentDomain.BaseDirectory + "\\Chloe.db;Version=3;Pooling=True;Max Pool Size=100;"));
            IQuery<Xwowmall_Day_Data> qd = dbcontext.Query<Xwowmall_Day_Data>();
            List<Xwowmall_Day_Data> xddlst = qd.Where(x => true).ToList();
            foreach (var item in xddlst)
            {
                string day = item.day;
                var xddy = xddlst.Where(x => x.thirdcataid == item.thirdcataid && x.day == Convert.ToDateTime(day).AddDays(-1).ToString("yyyy-MM-dd")).FirstOrDefault();
                if (xddy != null)
                {
                    item.morethanlast = item.totalsales - xddy.totalsales;
                }
            }


            DataTable tb = new DataTable();
            tb.Columns.Add(new DataColumn("日期", typeof(string)));
            tb.Columns.Add(new DataColumn("一级分类", typeof(string)));
            tb.Columns.Add(new DataColumn("二级分类", typeof(string)));
            tb.Columns.Add(new DataColumn("三级分类", typeof(string)));
            tb.Columns.Add(new DataColumn("上架数量", typeof(int)));
            tb.Columns.Add(new DataColumn("下架数量", typeof(int)));
            tb.Columns.Add(new DataColumn("销售数量", typeof(int)));
            tb.Columns.Add(new DataColumn("对比昨天", typeof(int)));

            foreach (var t in xddlst)
            {


                tb.Rows.Add(t.day, t.firstname, t.secondname, t.thirdname, t.upshelf, t.downshelf, t.totalsales, t.morethanlast);


            }
            StringBuilder sb = new StringBuilder();
            int tmpdataindex = 0;
            sb.Append("[");
            foreach (DataRow dr in tb.Rows)
            {
                sb.Append("{");
                foreach (var c in tb.Columns)
                {
                    sb.Append("\"" + c.ToString() + "\": \"" + dr[tmpdataindex++] + "\",");
                }

                sb.Remove(sb.Length - 1, 1);
                sb.Append("},");
                tmpdataindex = 0;
            }
            sb.Remove(sb.Length - 1, 1);
            sb.Append("]");

            return new JsonNetResult()
            {
                Data = JsonConvert.DeserializeObject(sb.ToString()),
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }
        #endregion

        public ActionResult DataSearch()
        {
            return View();
        }

        public JsonResult DataSearchAjac()
        {
            SQLiteContext dbcontext = new SQLiteContext(new SQLiteConnectionFactory("Data Source=" + System.AppDomain.CurrentDomain.BaseDirectory + "\\Chloe.db;Version=3;Pooling=True;Max Pool Size=100;"));
            IQuery<Xwowmall_Good> qd = dbcontext.Query<Xwowmall_Good>();
            List<Xwowmall_Good> lst = qd.Where(x => true).ToList();
            IQuery<Xwowmall_Cata> qc = dbcontext.Query<Xwowmall_Cata>();
            List<Xwowmall_Cata> mclst = qc.Where(x => true).ToList();
            XwowmallSearchModel vm = new XwowmallSearchModel();
            vm.code = 0;
            vm.msg = "";
            vm.count = lst.Count;
            vm.data = new List<Xwowmall_Good_Model>();
            foreach (var item in lst)
            {
                var mc3 = mclst.Where(x => x.cataid == item.cataid).FirstOrDefault();
                var mc2 = mclst.Where(x => x.cataid == mc3.parentid).FirstOrDefault();
                var mc1 = mclst.Where(x => x.cataid == mc2.parentid).FirstOrDefault();
                vm.data.Add(new Xwowmall_Good_Model()
                {
                    firstname = mc1.name,
                    secondname =mc2.name,
                    thirdname =mc3.name,
                    imgurl = item.imgurl,
                    price = item.price,
                    productname = item.productname,
                    shortdate = item.shortdate,
                    stock = item.stock
                });
            }
            return Json(vm, JsonRequestBehavior.AllowGet);
        }

        public FileResult Export(string start)
        {
            SQLiteContext dbcontext = new SQLiteContext(new SQLiteConnectionFactory("Data Source=" + System.AppDomain.CurrentDomain.BaseDirectory + "\\Chloe.db;Version=3;Pooling=True;Max Pool Size=100;"));
            IQuery<Xwowmall_Good> qd = dbcontext.Query<Xwowmall_Good>();
            List<Xwowmall_Good> lst = new List<Xwowmall_Good>();
            
            if (start!="")
            {
                
                lst = qd.Where(x => x.shortdate==start).ToList();
            }
            else
            {
                lst = qd.Where(x => true).ToList();
            }
            IQuery<Xwowmall_Cata> qc = dbcontext.Query<Xwowmall_Cata>();
            List<Xwowmall_Cata> mclst = qc.Where(x => true).ToList();
           
            var dataex = new List<Xwowmall_Good_Model>();
            foreach (var item in lst)
            {
                var mc3 = mclst.Where(x => x.cataid == item.cataid).FirstOrDefault();
                var mc2 = mclst.Where(x => x.cataid == mc3.parentid).FirstOrDefault();
                var mc1 = mclst.Where(x => x.cataid == mc2.parentid).FirstOrDefault();
                dataex.Add(new Xwowmall_Good_Model()
                {
                    firstname = mc1.name,
                    secondname = mc2.name,
                    thirdname = mc3.name,
                    imgurl = item.imgurl,
                    price = item.price,
                    productname = item.productname,
                    shortdate = item.shortdate,
                    stock = item.stock
                });
            }
            var tt = dataex.GroupBy(o => o.shortdate).Select(o => o.FirstOrDefault()).ToList();
            MemoryStream stream = ExcelHelper.Export(dataex,tt);

            return File(stream.ToArray(),
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "EPPlusDemo.xlsx");
        }


        public ActionResult ImprotToSqlite()
        {

            //SQLiteContext context = new SQLiteContext(new SQLiteConnectionFactory("Data Source=" + System.AppDomain.CurrentDomain.BaseDirectory + "\\Chloe.db;Version=3;Pooling=True;Max Pool Size=100;"));
            //MongoDbRepository _rep = new MongoDbRepository();
            //List<Mall_Cata> mclst = _rep.ToList<Mall_Cata>(x => true);
            //List<Xwowmall_Cata> xclst = new List<Xwowmall_Cata>();
            //mclst.ForEach(x =>
            //{
            //    xclst.Add(new Xwowmall_Cata()
            //    {
            //        cataid = x.cataid,
            //        cateleverl = x.cateleverl,
            //        modify = x.modify,
            //        name = x.name,
            //        parentid = x.parentid
            //    });
            //});       

            //context.InsertRange(xclst);

            //List<Mall_Good> mglst = _rep.ToList<Mall_Good>(x => true);
            //List<Xwowmall_Good> xglst = new List<Xwowmall_Good>();
            //mglst.ForEach(x =>
            //{
            //    xglst.Add(new Xwowmall_Good()
            //    {
            //        cataid = x.cataid,
            //        desc = x.desc,
            //        imgurl = x.imgurl,
            //        modify = x.modify,
            //        price = x.price,
            //        productid = x.productid,
            //        productname = x.productname,
            //        shortdate = x.shortdate,
            //        stock = x.stock
            //    });
            //});
            //context.InsertRange(xglst);
            return null;
        }
    }



    public class JsonNetResult : JsonResult
    {
        public JsonNetResult()
        {
            Settings = new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Error
            };
        }

        public JsonSerializerSettings Settings { get; private set; }

        public override void ExecuteResult(ControllerContext context)
        {
            if (context == null)
                throw new ArgumentNullException("context");
            if (this.JsonRequestBehavior == JsonRequestBehavior.DenyGet && string.Equals(context.HttpContext.Request.HttpMethod, "GET", StringComparison.OrdinalIgnoreCase))
                throw new InvalidOperationException("JSON GET is not allowed");

            HttpResponseBase response = context.HttpContext.Response;
            response.ContentType = string.IsNullOrEmpty(this.ContentType) ? "application/json" : this.ContentType;

            if (this.ContentEncoding != null)
                response.ContentEncoding = this.ContentEncoding;
            if (this.Data == null)
                return;

            var scriptSerializer = JsonSerializer.Create(this.Settings);

            using (var sw = new StringWriter())
            {
                scriptSerializer.Serialize(sw, this.Data);
                response.Write(sw.ToString());
            }
        }
    }


}

Study/ShenQi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <title>神器数据分析平台</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1, user-scalable=0" name="viewport">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta content="black" name="apple-mobile-web-app-status-bar-style">
    <meta content="telephone=no" name="format-detection">
    <link rel="stylesheet" href="~/layui/css/layui.css" />
    <link rel="stylesheet" href="~/css/admin.css" />
    <link rel="stylesheet" type="text/css" media="screen and (max-width:992px)" href="~/css/admin.mobile.css">

    <script type="text/javascript" src="~/js/vue.min.js"></script>
    <script type="text/javascript" src="~/layui/layui.js"></script>
 
</head>
<body>
    <div class="layui-layout layui-layout-admin">

        <!-- 头部 -->
        <div id="header">
            <header-component></header-component>
        </div>

        <!-- 遮罩层 -->
        <div class="masked"></div>

        <!-- 左侧菜单 -->
        <div id="leftSlide">
            <leftslide-component></leftslide-component>
        </div>

        <!-- 主体 -->
        <div class="layui-body">
            <!-- 主要内容 -->
            @RenderBody()

        </div>
    </div>

  
    <script type="text/javascript" src="~/js/fastclick.js"></script>
    <script>
        layui.use(["element", "layer"], function () {

            var $ = layui.jquery,
                element = layui.element,
                layer = layui.layer;
            $(function () {
                var l_o = $(".left-menu"),
                    tab = "top-tab",
                    l_m = "left-menu",
                    t_m = "top-menu";
                var mainHeight = $(window).height() - 60;
                l_o.on("click", "li", function () {
                    $(this).siblings().removeClass("layui-nav-itemed")
                });

                // 本地存储
                l_o.find("a[data-id]").click(function () {
                    sessionStorage.dataId = $(this).attr('data-id')
                });

                $(".menu-flexible").click(function () {
                    $(".left-menu-all").toggle();
                    $(".layui-body,.layui-footer").css("left", ($(".left-menu-all").is(":hidden")) ? "0" : "200px")
                });

                // 判断是否有本地存储
                if (sessionStorage.getItem('dataId')) {
                    var dataId = sessionStorage.getItem('dataId')
                    var getNowId = l_o.find("a[data-id=" + dataId + "]")
                    var getNowParent = $(getNowId).parent()

                    $(getNowParent).addClass('layui-this')
                    console.log($(getNowParent)[0]);
                    // 判断是否需要展开
                    if ($(getNowParent)[0].tagName == 'DD') {
                        $(getNowId).parents('.layui-nav-item').addClass('layui-nav-itemed');
                    }
                }
                // 目录
                $(document).on("click", ".mulu,.masked", function () {
                    $('body').toggleClass('mulu-hide');
                });

                document.body.addEventListener('touchstart', function () { });

            });



            // 搜索
            $(document).on('click', '#search-btn', function () {
                $('.search-res-mask').show();
                $(this).parent().siblings('.search-fix').addClass('cur');

            })

            $(document).on('click', '#search-close', function () {
                $('.search-res-mask').hide();
                $(this).parents('.search-fix').removeClass('cur');

            })

            $(document).on('click', '.search-res-mask', function () {
                $('#search-close').trigger('click');
            })

            // 移动端下拉
            $(document).on('click', '.layui-table .layui-table-first', function () {
                if ($(window).width() > 992) {
                    return;
                }
                if ($(this).hasClass('cur')) {
                    $(this).siblings().hide();
                    $(this).removeClass('cur');
                } else {
                    $($(this).siblings()).css('display', '-webkit-box');
                    $(this).addClass('cur');
                }
            })


        });


        var header = {
            template: `
        <!-- 头部 -->
        <div class="layui-header">
            <div class="layui-main">
                <div class="top-left">
                    <!-- logo -->
                    <a href="javascript:;" class="mulu"><img src="../img/mulu.png" alt=""></a>
                    <a href="javascript:;" class="logo">神奇数据分析平台</a>
                    <a href="javascript:;" class="menu-flexible ml10">
                        <i class="layui-icon">&#xe635;</i>
                    </a>
                </div>
                <!-- 头部右侧操作 -->
                <ul class="layui-nav operate">
                    <li class="layui-nav-item">
                        <a href="javascript:;">4829593</a>
                        <dl class="layui-nav-child">
                            <dd>
                                <a href="修改密码.html" class="edit-password">修改密码</a>
                            </dd>
                            <dd>
                                <a href="登录.html">退出登录</a>
                            </dd>
                        </dl>
                    </li>
                </ul>
            </div>
        </div>
        `
        };


        var leftSlide =
            {
                template: `
        <!-- 左侧菜单 -->
        <div class="layui-side layui-bg-black left-menu-all ">
            <div class="layui-side-scroll">
                <div class="info">
                    <div class ="name">4829593，欢迎您！</div>
                    <div class="oper box">
                        <a class="flex edit-password" href="#">修改密码</a>
                        <a class="flex" href="#">退出登录</a>
                    </div>
                </div>
                <ul class="layui-nav layui-nav-tree left-menu" lay-filter="left-menu">
                    <li class ="layui-nav-item">
                       <a href="@Url.Action("Index","Home")"  data-id="1">后台首页</a>

                    </li>
                    <li class="layui-nav-item">
                        <a href="javascript:;">Xwowmall分析</a>
                        <dl class ="layui-nav-child">
                                <dd>
                                    <a href="@Url.Action("Pivot","Xwowmall")"  data-id="2">报表分析</a>
                              
                                </dd>
                                <dd>
                                    <a href="@Url.Action("DataSearch","Xwowmall")"  data-id="3">数据查询</a>
                              
                                </dd>
                        </dl>
                    </li>
                    <li class="layui-nav-item">
                        <a href="javascript:;">哇宝分析</a>
                        <dl class ="layui-nav-child">
                            <dd>
                                <a href="@Url.Action("Pivot","Wabao")"  data-id="4">报表分析</a>
                         
                            </dd>
                            <dd>
                                <a href="@Url.Action("DataSearch","Wabao")"  data-id="5">数据查询</a>
                    
                            </dd>
                        </dl>
                    </li>

                </ul>
            </div>
        </div>
        `
            }

        // 创建根实例
        new Vue({
            el: '#header',
            components: {
                'header-component': header
            }

        })

        new Vue({
            el: '#leftSlide',
            components: {
                'leftslide-component': leftSlide
            }
        })



    </script>
</body>
</html>